name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: ./mvnw -B package
    - name: Upload to CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: target/site/jacoco/jacoco.xml
        fail_ci_if_error: true
